/******************************************************************************
 * $Id: tactics_pi.h, v1.0 2016/06/27 tom_BigSpeedy Exp $
 *
 * Project:  OpenCPN
 * Purpose:  Tactics Plugin
 * Author:   Thomas Rauch
 *   (Inspired by original work from Jean-Eudes Onfray)
 ***************************************************************************
 *   Copyright (C) 2010 by David S. Register                               *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,  USA.         *
 ***************************************************************************
 */

#ifndef __TacticsPreferencesDialogImpl__
#define __TacticsPreferencesDialogImpl__

/**
@file
Subclass of TacticsPreferencesDialogDef, which is generated by wxFormBuilder.
*/

#include "TacticsPreferencesDialogDef.h"

//// end generated include

/** Implementing TacticsPreferencesDialogDef */
class TacticsPreferencesDialogImpl : public TacticsPreferencesDialogDef
{
	protected:
		// Handlers for TacticsPreferencesDialogDef events.
		void OnTacticsPreferencesOKClick( wxCommandEvent& event );
		void OnTacticsPreferencesCancelClick( wxCommandEvent& event );
		void OnTacticsPreferencesApplyClick( wxCommandEvent& event );
        
	public:
		/** Constructor */
		TacticsPreferencesDialogImpl( wxWindow* parent );
	//// end generated class members

};

#endif // __TacticsPreferencesDialogImpl__
