/******************************************************************************
 * $Id: tactics_pi.h, v1.0 2016/06/27 tom_BigSpeedy Exp $
 *
 * Project:  OpenCPN
 * Purpose:  Tactics Plugin
 * Author:   Thomas Rauch
 *   (Inspired by original work from Jean-Eudes Onfray)
 ***************************************************************************
 *   Copyright (C) 2010 by David S. Register                               *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,  USA.         *
 ***************************************************************************
 */

#ifndef __TacticsPreferencesDialogImpl__
#define __TacticsPreferencesDialogImpl__

/**
 * @file
 * Subclass of TacticsPreferencesDialogDef, which is generated by wxFormBuilder.
 */

#include "TacticsPreferencesDialogDef.h"
#include "tactics_pi.h"

//// end generated include

// forward declare

/** Implementing TacticsPreferencesDialogDef */
class TacticsPreferencesDialogImpl : public TacticsPreferencesDialogDef
{
protected:
    // Handlers for tacticsPreferencesDialogDef events.
    void OnTacticsSelected( wxListEvent& event );
    void OnTacticsAdd( wxCommandEvent& event );
    void OnTacticsDelete( wxCommandEvent& event );
    void OnInstrumentSelected( wxListEvent& event );
    void OnInstrumentAdd( wxCommandEvent& event );
    void OnInstrumentDelete( wxCommandEvent& event );
    void OnInstrumentUp( wxCommandEvent& event );
    void OnInstrumentDown( wxCommandEvent& event );
    void OnManualHeelUpdate( wxCommandEvent& event );
    void ApplyPrefs( wxCommandEvent& event );
    void OnOKButtonClick( wxCommandEvent& event );
    void OnCancelButtonClick( wxCommandEvent& event );
    void OnApplyButtonClick( wxCommandEvent& event );
    void OnFontChanged( wxFontPickerEvent& event );
    void OnUpdateCtrl( wxSpinDoubleEvent& event );
    void OnUpdateCtrl( wxCommandEvent& event );
    
    void SaveTacticsConfig(void);
    void UpdateTacticsButtonsState(void);
    void getListItemForInstrument(wxListItem &item, unsigned int id);
    wxString getInstrumentCaption(unsigned int id);
    wxString GetUUID(void);
    int GetRandomNumber(int range_min, int range_max);
    void SaveChanges(void);
    void FontChanged( void );
    void UpdateCtrl( void );
    
    int  curSel;
    
public:
    /** Constructor */
    TacticsPreferencesDialogImpl( wxWindow* parent, wxString derivtitle, wxArrayOfTactics config );
    //// end generated class members
    
    void UpdateButtonsState(void);
    
    wxArrayOfTactics            m_Config;
    
};

#endif // __TacticsPreferencesDialogImpl__
