#ifndef __TacticsPreferencesDialogImpl__
#define __TacticsPreferencesDialogImpl__

/**
@file
Subclass of TacticsPreferencesDialogDef, which is generated by wxFormBuilder.
*/

#include "TacticsPreferencesDialogDef.h"

//// end generated include

/** Implementing TacticsPreferencesDialogDef */
class TacticsPreferencesDialogImpl : public TacticsPreferencesDialogDef
{
	protected:
		// Handlers for TacticsPreferencesDialogDef events.
		void OnTacticsPreferencesOKClick( wxCommandEvent& event );
		void OnTacticsPreferencesCancelClick( wxCommandEvent& event );
		void OnTacticsPreferencesApplyClick( wxCommandEvent& event );
	public:
		/** Constructor */
		TacticsPreferencesDialogImpl( wxWindow* parent );
	//// end generated class members

};

#endif // __TacticsPreferencesDialogImpl__
